# Generated by Django 5.1.4 on 2026-05-19 21:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('goal', models.CharField(choices=[('STRENGTH', 'Strength'), ('HYPERTROPHY', 'Hypertrophy'), ('ENDURANCE', 'Endurance'), ('WEIGHT_LOSS', 'Weight loss'), ('GENERAL_FITNESS', 'General fitness')], default='GENERAL_FITNESS', max_length=24)),
                ('frequency_per_week', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActiveWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day_index', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_workout_plan', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workout_plans.workoutplan')),
            ],
            options={
                'db_table': 'user_active_workout_plans',
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('target_muscle_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('SHOULDERS', 'Shoulders'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('LEGS', 'Legs'), ('GLUTES', 'Glutes'), ('CORE', 'Core'), ('FULL_BODY', 'Full body')], max_length=16), blank=True, default=list, size=None)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='workout_plans.workoutplan')),
            ],
            options={
                'db_table': 'routines',
                'ordering': ['workout_plan_id', 'day_index'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('target_sets', models.PositiveSmallIntegerField()),
                ('target_reps_min', models.PositiveSmallIntegerField()),
                ('target_reps_max', models.PositiveSmallIntegerField()),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('exercise_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exercise_catalog.exercisetemplate')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_plans.routine')),
            ],
            options={
                'db_table': 'routine_exercises',
                'ordering': ['routine_id', 'position'],
                'constraints': [models.UniqueConstraint(fields=('routine', 'position'), name='routine_exercise_unique_position')],
            },
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['user', '-created_at'], name='workout_pla_user_id_07d109_idx'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(fields=('workout_plan', 'day_index'), name='routine_unique_day_index_per_plan'),
        ),
    ]
