# Generated by Django 5.1.4 on 2026-05-19 21:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('primary_muscle_group', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('SHOULDERS', 'Shoulders'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('LEGS', 'Legs'), ('GLUTES', 'Glutes'), ('CORE', 'Core'), ('FULL_BODY', 'Full body')], max_length=16)),
                ('secondary_muscle_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('SHOULDERS', 'Shoulders'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('LEGS', 'Legs'), ('GLUTES', 'Glutes'), ('CORE', 'Core'), ('FULL_BODY', 'Full body')], max_length=16), blank=True, default=list, size=None)),
                ('equipment', models.CharField(choices=[('BARBELL', 'Barbell'), ('DUMBBELL', 'Dumbbell'), ('MACHINE', 'Machine'), ('CABLE', 'Cable'), ('BODYWEIGHT', 'Bodyweight'), ('KETTLEBELL', 'Kettlebell'), ('BAND', 'Resistance band')], max_length=16)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=16)),
                ('instructions', models.TextField(blank=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercise_templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['primary_muscle_group'], name='exercise_te_primary_69564a_idx'), models.Index(fields=['-usage_count'], name='exercise_te_usage_c_b96387_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseTemplateAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('locale', models.CharField(default='en', max_length=8)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='exercise_catalog.exercisetemplate')),
            ],
            options={
                'db_table': 'exercise_template_aliases',
                'indexes': [models.Index(fields=['locale', 'name'], name='exercise_te_locale_70c3dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'locale'), name='exercise_alias_unique_name_per_locale')],
            },
        ),
    ]
