# Generated by Django 5.1.4 on 2026-05-19 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('workout_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'followings',
                'indexes': [
                    models.Index(fields=['followed', 'follower'], name='followings_followe_e006f4_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('follower', 'followed'), name='following_unique_pair'),
                    models.CheckConstraint(condition=models.Q(('follower', models.F('followed')), _negated=True), name='following_no_self_follow'),
                ],
            },
        ),
        migrations.CreateModel(
            name='WorkoutComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_comments', to=settings.AUTH_USER_MODEL)),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workout_sessions.workoutsession')),
            ],
            options={
                'db_table': 'workout_comments',
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(fields=['workout_session', 'created_at'], name='workout_com_workout_1eac8c_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_likes', to=settings.AUTH_USER_MODEL)),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='workout_sessions.workoutsession')),
            ],
            options={
                'db_table': 'workout_likes',
                'indexes': [
                    models.Index(fields=['workout_session', '-created_at'], name='workout_lik_workout_87681f_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('user', 'workout_session'), name='workout_like_unique_per_user'),
                ],
            },
        ),
    ]
