# Generated by Django 5.1.4 on 2026-05-19 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('exercise_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exercise_catalog.exercisetemplate')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_sessions.workoutsession')),
            ],
            options={
                'db_table': 'workout_session_exercises',
                'ordering': ['workout_session_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSessionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reps', models.PositiveSmallIntegerField()),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('completed_at', models.DateTimeField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workout_sessions.workoutsessionexercise')),
            ],
            options={
                'db_table': 'workout_session_sets',
                'ordering': ['exercise_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('best_reps_at_weight', models.PositiveSmallIntegerField()),
                ('achieved_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exercise_catalog.exercisetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
                ('source_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workout_sessions.workoutsessionset')),
            ],
            options={
                'db_table': 'personal_records',
            },
        ),
        migrations.CreateModel(
            name='MuscleGroupRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('SHOULDERS', 'Shoulders'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('LEGS', 'Legs'), ('GLUTES', 'Glutes'), ('CORE', 'Core'), ('FULL_BODY', 'Full body')], max_length=16)),
                ('last_trained_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_group_recoveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'muscle_group_recoveries',
                'constraints': [models.UniqueConstraint(fields=('user', 'muscle_group'), name='muscle_group_recovery_unique_per_user')],
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', '-started_at'], name='workout_ses_user_id_35f23a_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutsessionexercise',
            constraint=models.UniqueConstraint(fields=('workout_session', 'position'), name='workout_session_exercise_unique_position'),
        ),
        migrations.AddIndex(
            model_name='workoutsessionset',
            index=models.Index(fields=['-completed_at'], name='workout_ses_complet_53449b_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutsessionset',
            constraint=models.UniqueConstraint(fields=('exercise', 'position'), name='workout_session_set_unique_position_per_exercise'),
        ),
        migrations.AddConstraint(
            model_name='personalrecord',
            constraint=models.UniqueConstraint(fields=('user', 'exercise_template'), name='personal_record_unique_per_user_exercise'),
        ),
    ]
